# Generated by Django 5.1.4 on 2025-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text='File name in project/static/project/images/', max_length=100, null=True),
        ),
    ]
