# Generated by Django 5.1.4 on 2025-05-18 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.FileField(default='no logo', help_text='svg file for skill image', upload_to='skill_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
            preserve_default=False,
        ),
    ]
