# Generated by Django 5.1.4 on 2025-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.CharField(help_text='File name in cv/static/cv/images/', max_length=100),
        ),
    ]
